source 'https://github.com/LovePlayModule/Podspec.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'NewsCommentModule_Example' do
  pod 'NewsCommentModule', :path => '../'

  pod 'Network'
  pod 'Tools'

  pod 'YYKit'
  pod 'Masonry'
  target 'NewsCommentModule_Tests' do
    inherit! :search_paths

    
  end
end
